"""Generate exact group/name/checksum primitive types from reviewed wire evidence.

Unlike donor checksum propagation, these entries never apply to another group
or another field name. The evidence fixture is explicit; this tool does not
infer types from widths or names. Run again after editing the fixture, and use
--check to detect stale generated Rust.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from atomic_io import atomic_write_text

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "tools/fixtures/scoped_type_evidence.json"
OUTPUT = ROOT / "crates/vrf-decode/src/scoped_types.rs"
TYPES = {"Byte", "Bool", "Int32", "UInt32", "Float", "Double", "FString", "ObjectNetGuid"}


def load(path: Path) -> list[dict]:
    document = json.loads(path.read_text(encoding="utf-8"))
    if document.get("schema_version") != 1:
        raise ValueError("expected scoped evidence schema_version 1")
    entries = document.get("entries")
    if not isinstance(entries, list) or not entries:
        raise ValueError("expected non-empty entries")
    seen = set()
    for entry in entries:
        for key in ("group", "field", "evidence"):
            if not isinstance(entry.get(key), str) or not entry[key].strip():
                raise ValueError(f"missing {key}")
        if not entry["group"].isascii() or not entry["field"].isascii():
            raise ValueError("Rust field identities must be ASCII")
        checksum = entry.get("checksum")
        if type(checksum) is not int or not 0 < checksum <= 0xFFFFFFFF:
            raise ValueError("checksum must be a nonzero u32")
        if entry.get("type") not in TYPES:
            raise ValueError("unsupported primitive type")
        builds = entry.get("observed_builds")
        if not isinstance(builds, list) or not builds or any(not isinstance(b, str) or not b for b in builds):
            raise ValueError("observed_builds must record the replay evidence scope")
        key = (entry["field"], entry["group"], checksum)
        if key in seen:
            raise ValueError(f"duplicate scoped identity: {key}")
        seen.add(key)
    return sorted(entries, key=lambda e: (e["field"], e["group"], e["checksum"]))


def render(entries: list[dict]) -> str:
    lines = [
        "//! Generated by `tools/generate_scoped_types.py`; do not edit by hand.",
        "//! Exact field identities whose names alone are ambiguous.",
        "//! Observed build scope and wire evidence live in the source fixture.",
        "", "use crate::decode::FieldType;", "",
        "/// Sorted by (field name, group path, compatible checksum).",
        f"pub(crate) static SCOPED_TYPES: [(&str, &str, u32, FieldType); {len(entries)}] = [",
    ]
    for entry in entries:
        lines += ["    (", f"        {json.dumps(entry['field'])},",
                  f"        {json.dumps(entry['group'])},",
                  f"        {entry['checksum']},", f"        FieldType::{entry['type']},", "    ),"]
    return "\n".join(lines + ["];", ""])


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence", type=Path, default=EVIDENCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        entries = load(args.evidence)
        text = render(entries)
        if args.check:
            if not args.output.is_file() or args.output.read_text(encoding="utf-8") != text:
                print("ERROR: scoped type table differs from reviewed evidence")
                return 1
        else:
            atomic_write_text(args.output, text)
        print(f"OK: {len(entries)} scoped primitive types")
        return 0
    except (ValueError, OSError, KeyError, TypeError) as exc:
        print(f"ERROR: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
